[project]
name = "gui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ldap3>=2.9.1",
    "pydantic-settings>=2.13.0",
    "pyside6>=6.10.2",
]
# isort
[tool.isort]
profile = "black"
py_version = "312"
line_length = "120"
use_parentheses = true
include_trailing_comma = true
combine_as_imports = false
force_sort_within_sections = true
import_heading_stdlib = "Standard Library"
import_heading_thirdparty = "Third Library"
known_first_party = []
known_third_party = ["pyside6", "ldap3"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
# black
[tool.black]
include = '^(?!.*main\.py).*\.py$'
line-length = 120
target-version = ['py312']
exclude = '''/.git|/.ruff_cache|/.venv|/__pycache__|output.*|base.*|_asset.*'''
